### ISSUE TITLE
Run a phar instead of php files.

### ISSUE THREAD

**Issue by blazarecki** [iamluc/docker-hostmanager#3]
This allow to run the hostmanager without docker.

**Comment by iamluc** [comment]
I recommand to use http://box-project.github.io/box2/ for creating a phar.

Box needs a simple configuration file like this one https://github.com/iamluc/buse/blob/master/box.json

**Comment by iamluc** [comment]
#5

**Comment by iamluc** [comment]
Fixed by #13
